# This docker-compose.yml is configured to simulate a production environment for local testing.

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: api
    env_file:
      - ./.env
    environment:
      BUNDLE_PATH: vendor/bundle
      WICKED_PDF_PATH: /usr/bin/wkhtmltopdf
      BUNDLE_WITHOUT: development:test:mysql:aws:sandbox:ci:wkhtmltopdf
      RAILS_ENV: production
      NODE_ENV: production
      LC_ALL: en_CA.UTF-8
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["bundle", "exec", "rails", "s"]
  
  # web service to serve static files via Nginx and proxy requests to api service (Rails app)
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: web
      args:
        SERVER_NAME: '127.0.0.1'
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  db_volume:
