name: Tests - MySQL

on: [push, pull_request]

jobs:
  mysql:
    runs-on: ubuntu-20.04

    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
      with:
        ruby-version: 2.7.6
        bundler-cache: true

    # Install Node
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client-core-8.0 
        sudo apt-get install -y mysql-server
        sudo apt-get install -y libmysqlclient-dev 

    - name: 'Determine Ruby and Bundler Versions from Gemfile.lock'
      run: |
        echo "RUBY_VERSION=`cat ./Gemfile.lock | grep -A 1 'RUBY VERSION' | grep 'ruby' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    # Copy all of the example configs over
    - name: 'Setup the application'
      run: |
        # Make copies of all the example config files
        cp config/database.yml.sample config/database.yml
        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb
        cp .env.mysql2 .env

    # Stub out the Rails credentials file so that we can start the Rails app
    - name: 'Setup Credentials'
      run: EDITOR='echo "$(cat config/credentials.yml.mysql2)" >' bundle exec rails credentials:edit

    - name: 'Determine wkhtmltopdf location'
      run: echo "WICKED_PDF_PATH=`bundle exec which wkhtmltopdf`" >> $GITHUB_ENV

    - name: 'Yarn Install'
      run: |
        yarn install

    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Build out the test database'
      run: |
        bundle exec rails db:create RAILS_ENV=test
        bundle exec rails db:schema:load RAILS_ENV=test

    - name: 'Run any pending database migrations'
      run: bin/rails db:migrate RAILS_ENV=test

    # Prebuild the CSS, JS and image assets
    - name: 'Precompile all of the Assets'
      run: bundle exec rails assets:precompile

    - name: 'Run Rspec Unit and Functional Tests'
      run: |
        bundle exec rspec spec/models/ spec/policies/ spec/services/ spec/helpers/
        bundle exec rspec spec/controllers/ spec/presenters/ spec/requests/ spec/views
        bundle exec rspec spec/mixins/

    # Only run Integration tests if the PR or Push is to master or development branches
    - name: 'Run Rspec Integration Tests'
      run: bundle exec rspec spec/features/
