name: Rubocop

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: 'Determine Ruby and Bundler Versions from Gemfile.lock'
      run: |
        echo "RUBY_VERSION=`cat ./Gemfile.lock | grep -A 1 'RUBY VERSION' | grep 'ruby' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    # Install Ruby - using the version found in the Gemfile.lock
    - name: 'Install Ruby'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler-cache: true

    - name: 'Run Rubocop'
      run: bin/rubocop
